= This is the documentation file for team TWELVE.

=== Team members and their main roles are:

* Pille Pärnalaas - Programming
* Kenno Kallastu - Mechanics
* Stepan Denysenko - Electronics

=== Public Fusion 360 project for mechanics
(Currently the test robot, will be updated to the actual robot when it's done)
Link: https://a360.co/3haaYUI

== DAILY BLOG

=== 03.09
====== BOOTCAMP DAY ONE
Kenno, Pille:: present and working the tasks (both 8h)

=== 14.09
First gathering of the team. Divided main roles and started work.

Kenno:: Omnidirectional wheels attached to the chassis along with the motors. Helped with electronics. 
	Getting familiar with the lab.(1.5h)
Stepan:: Wired, soldered. (1.5h)
Pille:: Took home the NUC for initial setup. (1h)

=== 15.09 
Kenno:: Reading the guides. Rough planning of the design process, was pretty overwhelmed and didn't 
	understand what was supposed to be done. (1h)

=== 17.09

Pille:: Made an Ubuntu image for the computer. Installed Ubuntu, configured setup.
	Got some errors when installing the segment module. (1.5h)

=== 18.09

Pille:: Got the bootcamp example code running. Tried to write commands for sending over serial.
	Need to test out with hardware.
	Tried to upload daily blog to git, encountered problems.
	(2h)

=== 19.09

Pille:: project progress presentation + slides (2h)
Kenno, Stepan:: Present at project progress presentations (1.5h)

=== 20.09

Pille:: working on the git repo issues. Connecting over ssh. (1h)

=== 22.09

Kenno:: Thrower measurements for CAD. Swapped the M3 bolts on the electric motor mount to 
	shorter ones. (1h10min)
Pille:: Programming. Got the serial connection working. Needs some additional code to connect even 
	if the port changes. (2h)
Stepan:: Fixed faulty wiring. (1h)

=== 26.09

Pille:: 
	* Fixed github commit issues I had to upload bootcamp code to the git folder. Connected the mainboard wires to the motors. Works! (0.5h)
	* Tested serial connection over HTerm and with the bootcamp code task. Works! (0.5h)
	* Sorted the serial ports so that the robot will always connect to the right port even if the name changes. Next task is using the camera and detecting the ball. (0.5h)

=== 28.09

Pille::
	* Edited the blog with spent time, read the battery instructions. (1h)
	* Team management. (15min)
Kenno:: Imported test robot files into Fusion 360, started with the thrower design, watched tutorials. (2h)

=== 29.09

Pille:: Got the battery briefing. Tested the robot with a battery. Found some faulty wiring. (1.5h)
Stepan:: Got the battery briefing. Tested the robot with a battery. Found out that the on/off switch is faulty and needs to be replaced. (2h)

=== 30.09

Kenno:: Gathering intel from previous years, even more CAD tutorials, thrower is almost ready. (3h)

=== 01.10

Pille::
	* Progress presentation slides, blog entries. Team management. (0.5h)
	* Edited the code to move wheel for given time. Made a separate function to make the code more readable. (0.5h)

=== 02.10

Pille:: 
	* Team management issues. (30min)
	* Reediting the daily blog (15min)
	
=== 03.10

Kenno:: Finished the first thrower design, slides for presentation. (1h)

Pille:: Presenting progress and resolving team issues. (2h)

=== 05.10

Pille:: 
	* Filling in the project time planning tool, sending to other team members (30min).
	* Cleaning up the main.py file, moving serial connection to motion class. Starting with driving logic. (30min)
	* Working on the driving logic, need to figure out the speed calculations. (1h15min)

=== 06.10

Kenno::
	* Actual robot thrower should be completed. (2h)
	* Test-robot electronics bolted onto the chassis. Minor attachments. (2h)

Pille:: Programming robot moving logic. (2h)

=== 10.10

Kenno:: 
	* New test robot thrower as the first design had issues. (2h30min)
	* Messing with the joining, gave the thrower for first review, needs dogbones to be ready (1h)

Pille::
	* Started re-soldering the test robots battery to NUC connections as one of the plugs was wrong. Stepan took over. (30min)
	* Trying to get remote access to the robot computer set up. Still doesn't work correctly. (1h15min)
	* The test robot is finally assembled, I could test the code in action. Robot drives straight and is able to follow the ball. (45min)

=== 12.10

Pille:: Editing the code as requested by the instructor. (1h)

=== 13.10

Pille:: Screwing in final bolts to the test-robot frame. (20min)

=== 16.10

Pille:: Progress presentation slides for monday. (20min)

=== 17.10

Kenno:: On-site presentation and valuable info for the team. (1h15min)

=== 18.10

Kenno:: Fixed the thrower issues that were pointed out after the review. (2h)

=== 19.10

Kenno:: Fixed the new issues of the thrower. (1h)

=== 20.10

Pille:: Programming the ball following logic, presenting to the instructor. Calibrating color configuration. (2.5h)

=== 26.10

Kenno:: First CAM for the test robot thrower done. (2h)

=== 27.10

Kenno:: CAM final adjustments and milling out the parts. (2h)
Pille:: Onsite code testing. Color configurations, trying to setup remote acces with camera view. Failed. (1h)

=== 29.10

Pille:: 
	* Slides for mondays presentation. Uploading video. (20min)
	* Starting the programming on robot finding basket. How to orbit? (45min)

=== 30.10

Stepan:: Started working on PCB schematics. (10h)

=== 31.10

Pille:: Presentation on site. (1h)

=== 01.11

Kenno:: Attached the thrower to the test robot. (3h)
Pille:: Modification of the code after feedback from instructor. (30min)

=== 03.11

Pille:: 
	* Programming the ball throwing logic. Still have questions. (1h)
	* Programming - adding referee command listening (30min)
	* Programming on site - trying to get camera image when remote connection, failed, still have qt5 error. (1h30min)
	* Programming on site - testing the code, rewriting logic to find basket and orbit the ball. It is now proportional. (2h)
	* Commenting the code. (30min)
